name: Deploy to Cloudflare Workers
on:
  push:
    branches: [main]  # 推送到 main 分支时触发
  workflow_dispatch:  # 允许手动触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # 检出代码到工作流环境

      - name: Deploy with Wrangler
        uses: cloudflare/wrangler-action@3.0.0  # 使用 Cloudflare 官方 Action
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}  # 引用密钥
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}"# ????" 
